version: "3.8"

services:
  # ── Datastores ────────────────────────────────────────────────────────────────
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  # ── Microservices ────────────────────────────────────────────────────────────
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis

  checkout-service:
    build:
      context: ./checkout-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  mongo-data:
  redis-data:
  pg-data:
